### ISSUE TITLE
yace format cannot be read by python

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE.jl#102]
The default YAML reader (PyYAML?) cannot read yace format potentials as currently written, because they can include dictionaries that have lists as keys, while python only supports tuples as keys.  Here's an example of a format that's produced, problem is on line 7.  

This is really a big deal, since it's just meant to be read by the LAMMPS PACE package, but it would be convenient if a mutually understandable format could be used, so feel free to close it if it's not easy to solve.
```
deltaSplineBins: 0.001
E0:
  - -0.0046603
  - 0.0
  - 0.0
bonds:
  [0, 0]:
    rcut: 3.6
    xl: 0.37051039697542537
    recursion_coefficients:
      B:
        - 0.0
        - -5.913670422702299
        - -4.767753518631563
        - -4.334321380574182
        - -4.1097011882705266
        - -3.974709174650009
      A:
        - 31.295482159646728
        - 7.009373160773004
        - 5.651137307615811
        - 5.137397552378055
        - 4.871159051622799
        - 4.711155309520793
      C:
        - 0.0
        - 0.0
        - -0.8062257748298575
        - -0.9090909090909122
        - -0.9481763873555094
        - -0.9671528397232746
    pl: 2
    radbasename: "ACE.jl.base"
    r0: 1.8
    xr: 1.3168503090567045
    maxn: 6
    pr: 2
    p: 2
```
